name: Build and Release Chrome Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip extension
        run: zip -r formina.zip src

      - name: Upload files to existing release
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            const fs = require('fs');
            const tag = context.payload.release.tag_name;

            // Get the release for this tag
            const release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag
            });

            // Upload the release asset
            await github.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: "formina.zip",  // Change this to your file's name
              data: fs.readFileSync("formina.zip")  // Specify the path to your file
            });